language: python
python:
    - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install pytest pycodestyle pytest-cov
script:
  - pytest --cov=skill --cov-fail-under=8
  - pycodestyle skill --max-line-length 120
