- q:
    - привет
    - приветики
    - здравствуй
    - здравствуйте
    - здрасте
    - добрый день
    - добрый вечер
    - доброе утро
  a:
    - И вам привет!
    - Приветствую вас, человек!
    - И вы здравствуйте.
    - Привет! Какой навык хотите найти?
    - Привет-привет
  s:
    - найди навык про кровь
    - найди доставку суши
    - какой навык учит математику

- q:
    - алиса
    - а
    - поиск навыков
    - поиск навыков каталог алисы
    - навык
  a:
    - Вы находитесь в навыке "Искатель навыков". Какой навык вы хотите найти?
  s:
    - навык смешарики
    - быстрая тренировка
    - навык про костный мозг

- q:
    - горшок
    - навык горшок
    - голосовой помощник горшок
  a: К сожалению, навык "Голосовой помощник Горшок" был удалён. Но вы можете найти другие весёлые навыки!

- q:
    - можно сделать свой навык
    - как сделать свой навык
    - как создать свой собственный навык
  a: 'Создать собственный навык в Алисе может каждый.
      Конечно, придётся немножко повозиться.
      Для начала, прочитайте документацию на сайте Яндекс Диалогов.
      <a href="https://dialogs.yandex.ru" hide=false>сайт</a>'
