- q:
    - привет
    - приветики
    - здравствуй
    - здравствуйте
    - здрасте
  a:
    - И вам привет!
    - Приветствую вас, человек!
    - И вы здравствуйте.
    - Привет! Какой навык хотите найти?
    - Привет-привет
  s:
    - найди навык про кровь
    - найди доставку суши
    - какой навык учит математику

- q:
    - алиса
    - а
  a:
    - Вы находитесь в навыке "Искатель навыков". Какой навык вы хотите найти?

- q:
    - горшок
    - навык горшок
    - голосовой помощник горшок
  a: К сожалению, навык "Голосовой помощник Горшок" был удалён. Но вы можете найти другие весёлые навыки!
