
next_skills:
  examples:
    - алиса а остальные расскажи
    - ещё
    - еще
    - дальше
    - еще варианты
    - еще надо
    - направо

prev_skills:
  examples:
    - предыдущие
    - назад
    - налево

run_skill:
  regexp: '(алиса )?(запусти|открой|включи)( пожалуйста)?( мне| нам)? (навык|игру).+'

exit_skill:
  examples:
    - выйти из навыка
    - выход из навыка

get_skill_details:
  regexp: 'расскажи про подробнее про навык'

repeat:
  examples:
    - что
    - повтори
    - еще раз
